{config, pkgs, ...}:
{
  home.packages = with pkgs; [
     appimage-run
     arandr
     betterlockscreen
     bitwarden
     brave
     discord
     element-desktop
     feh
     firefox
     flameshot
     font-manager 
     galculator
     geany
     gimp-with-plugins
     glances
     google-chrome
     hplipWithPlugin
     htop
     keepassxc
     imagemagick
     libreoffice
     lxappearance
     meld
     networkmanagerapplet
     nitrogen
     oh-my-zsh
     pcmanfm
     picom
     polkit_gnome
     polybar
     signal-desktop
     telegram-desktop
     tor
     tor-browser-bundle-bin
     torsocks
     udiskie
     udisks
     veracrypt
     viewnior
     vlc
     volumeicon
     #yubikey-agent
     #yubikey-manager
     #yubioath-flutter
     zsh-powerlevel10k

 #Themes
     dracula-theme
     dracula-icon-theme
     catppuccin-gtk 
     catppuccin-kde
     catppuccin-cursors.mochaDark
     catppuccin
 
   ];
}
