# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-c6ba1dc8-ea7f-4e52-a88f-a3c435c03669";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-c6ba1dc8-ea7f-4e52-a88f-a3c435c03669".device = "/dev/disk/by-uuid/c6ba1dc8-ea7f-4e52-a88f-a3c435c03669";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-c6ba1dc8-ea7f-4e52-a88f-a3c435c03669";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-c6ba1dc8-ea7f-4e52-a88f-a3c435c03669";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0099-0340";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-2ac340d9-644c-4e61-80a7-ceb55558c104"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
